language: java
branches:
  only:
  - master
  - /feature/.*$/
 
jdk: openjdk9

services:
  - docker

cache:
   directories:
      - $HOME/.m2

script:
  - cd docker && docker-compose up --build --abort-on-container-exit 
after_script:
  - docker-compose down --remove-orphans